export interface FinanceOpeningRow {
  sku: string;
  purchaseUnitPrice: string;
  defaultSalePrice: string;
  unitsPurchased: number;
  unitsSold: number;
  actualSalePrice: string | null;
}

// Approved screenshot, 2026-09-21 12:53:40. Values are AMD.
export const financeOpeningData: readonly FinanceOpeningRow[] = [
  {
    sku: "TRPRCH",
    purchaseUnitPrice: "19000",
    defaultSalePrice: "24000",
    unitsPurchased: 4,
    unitsSold: 1,
    actualSalePrice: "24000",
  },
  {
    sku: "TRPRCHCOC",
    purchaseUnitPrice: "19000",
    defaultSalePrice: "24000",
    unitsPurchased: 4,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRPRVN",
    purchaseUnitPrice: "19000",
    defaultSalePrice: "24000",
    unitsPurchased: 4,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRPRCK",
    purchaseUnitPrice: "19000",
    defaultSalePrice: "24000",
    unitsPurchased: 4,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRPRSTR",
    purchaseUnitPrice: "19000",
    defaultSalePrice: "24000",
    unitsPurchased: 4,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRCOL",
    purchaseUnitPrice: "12000",
    defaultSalePrice: "16500",
    unitsPurchased: 5,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRGAIN",
    purchaseUnitPrice: "25000",
    defaultSalePrice: "30000",
    unitsPurchased: 4,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRCRMEN",
    purchaseUnitPrice: "9000",
    defaultSalePrice: "14000",
    unitsPurchased: 5,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRBCA",
    purchaseUnitPrice: "5500",
    defaultSalePrice: "9000",
    unitsPurchased: 6,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRFLEX",
    purchaseUnitPrice: "15000",
    defaultSalePrice: "17500",
    unitsPurchased: 2,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRLCAR500",
    purchaseUnitPrice: "10000",
    defaultSalePrice: "13000",
    unitsPurchased: 2,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRLCAR100",
    purchaseUnitPrice: "830",
    defaultSalePrice: "1500",
    unitsPurchased: 24,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRLCARCOMP",
    purchaseUnitPrice: "7000",
    defaultSalePrice: "13000",
    unitsPurchased: 2,
    unitsSold: 1,
    actualSalePrice: "13000",
  },
  {
    sku: "TRPROZM",
    purchaseUnitPrice: "11000",
    defaultSalePrice: "15000",
    unitsPurchased: 2,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRCAFF",
    purchaseUnitPrice: "4000",
    defaultSalePrice: "6500",
    unitsPurchased: 2,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRVITFM",
    purchaseUnitPrice: "5000",
    defaultSalePrice: "9900",
    unitsPurchased: 5,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRVITFWM",
    purchaseUnitPrice: "5000",
    defaultSalePrice: "9900",
    unitsPurchased: 5,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TROMG",
    purchaseUnitPrice: "5500",
    defaultSalePrice: "9000",
    unitsPurchased: 5,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRMAGNE",
    purchaseUnitPrice: "4000",
    defaultSalePrice: "6500",
    unitsPurchased: 4,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRBOOG100",
    purchaseUnitPrice: "830",
    defaultSalePrice: "1500",
    unitsPurchased: 24,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRBOOG500",
    purchaseUnitPrice: "14000",
    defaultSalePrice: "18000",
    unitsPurchased: 1,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "1RCRE",
    purchaseUnitPrice: "7000",
    defaultSalePrice: "13000",
    unitsPurchased: 17,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "1RPREC4HD",
    purchaseUnitPrice: "10500",
    defaultSalePrice: "15000",
    unitsPurchased: 4,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "1RPREC4SMD",
    purchaseUnitPrice: "10500",
    defaultSalePrice: "14000",
    unitsPurchased: 3,
    unitsSold: 0,
    actualSalePrice: null,
  },
  {
    sku: "TRGLUT",
    purchaseUnitPrice: "10000",
    defaultSalePrice: "15000",
    unitsPurchased: 1,
    unitsSold: 0,
    actualSalePrice: null,
  },
];
